{
    "name": "Helpdesk Sale Order Account Move Link",
    "version": "16.0.1.0.0",
    "category": "Services/Helpdesk",
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "license": "Other proprietary",
    "summary": "Bridges helpdesk_sale_order_link and " "helpdesk_account_move_link",
    "depends": [
        "helpdesk",
        "sale_management",
        "helpdesk_sale_order_link",
        "helpdesk_account_move_link",
    ],
    "data": [],
    "assets": {},
    "demo": [],
    "external_dependencies": {},
    "price": 0.0,
    "currency": "EUR",
    "support": "info@glo.systems",
    "application": False,
    "installable": True,
    "auto_install": False,
}
