{
    "name": "Connector Edi",
    "summary": "Base EDI module",
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "category": "Tools",
    "version": "17.0.1.0.0",
    "depends": [
        "base_setup",
        "base_sparse_field",
        "connector",
        "component",
        "queue_job",
    ],
    "data": [
        "views/edi_message.xml",
        "views/edi_envelope.xml",
        "views/edi_backend.xml",
        "views/edi_message_route.xml",
        "views/edi_route_event.xml",
        "views/edi_envelope_route.xml",
        "views/menu.xml",
        "security/ir.model.access.csv",
        "data/edi_route_event.xml",
        "data/edi_sequences.xml",
        "data/mail.xml",
        "data/ir_cron.xml",
        "wizards/edi_upload_file.xml",
    ],
    "images": [],
    "demo": [],
    "external_dependencies": {"bin": [], "python": ["requests", "lxml"]},
    "license": "LGPL-3",
}
