{
    "name": "Connector EDI",
    "summary": "Base EDI module",
    "version": "18.0.1.0.0",
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "depends": [
        "base_setup",
        "base_sparse_field",
        "component",
        "connector",
        "queue_job",
    ],
    "data": [
        "data/edi_route_event_data.xml",
        "data/ir_cron_data.xml",
        "data/ir_sequence_data.xml",
        "data/mail_message_subtype_data.xml",
        "security/ir.model.access.csv",
        "views/edi_backend_views.xml",
        "views/edi_envelope_route_views.xml",
        "views/edi_envelope_views.xml",
        "views/edi_message_route_views.xml",
        "views/edi_message_views.xml",
        "views/edi_route_event_views.xml",
        "views/menu_views.xml",
        "wizards/edi_upload_file_views.xml",
    ],
    "external_dependencies": {"python": ["lxml", "requests"]},
    "license": "Other proprietary",
}
