# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: Glo Networks
org_slug: GlodoUK
rebel_module_groups: []
repo_description: Odoo web client related addons
repo_name: Odoo web client related addons
repo_slug: web
repo_website: https://github.com/GlodoUK/web
use_pyproject_toml: false
use_ruff: false

