# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.8.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Glo Networks
org_slug: GlodoUK
rebel_module_groups: []
repo_description: Odoo Partner and Contact related addons
repo_name: Odoo Partner and Contact related addons
repo_slug: partner-contact
repo_website: https://github.com/GlodoUK/partner-contact
travis_apt_packages: []
travis_apt_sources: []

