# Do NOT update manually; changes here will be overwritten by Copier
<<<<<<< HEAD
_commit: v1.14.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
=======
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: false
>>>>>>> odoo-addons/15.0
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
<<<<<<< HEAD
=======
odoo_test_flavor: Odoo
>>>>>>> odoo-addons/15.0
odoo_version: 15.0
org_name: Glo Networks
org_slug: GlodoUK
rebel_module_groups: []
<<<<<<< HEAD
repo_description: This project aims to deal with modules related to the purchase modules
    of Odoo.
repo_name: Purchase related addons for Odoo
repo_slug: purchase
repo_website: https://github.com/GlodoUK/purchase
travis_apt_packages: []
travis_apt_sources: []
=======
repo_description: This repository houses addons for many areas of Odoo. It is an amalgamation
    of multiple previous repositories (GlodoUK/sale, web, etc.)
repo_name: Addons for Odoo
repo_slug: odoo-addons
repo_website: https://github.com/GlodoUK/odoo-addons
use_pyproject_toml: true
use_ruff: true
>>>>>>> odoo-addons/15.0

