{
    "version": "12.0.1.0.0",
    "name": "prometheus",
    "summary": """Monkey patches Odoo to install prometheus timings for http
    requests and sql queries.""",
    "category": "Hidden",
    # 'live_test_url': "",
    "images": [],
    "application": False,
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "license": "Other proprietary",
    "depends": ["base"],
    "external_dependencies": {"python": ["prometheus_client"], "bin": []},
    "data": [],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
