version: "3.8"

services:
  odoo:
    build:
      dockerfile: .ci/Dockerfile
      context: ../
      args:
        ODOO_VERSION: "19.0"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGDATABASE=odoo
      - PGUSER=odoo
      - PGHOST=db
      - PGPASSWORD=odoo
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/data:z

volumes:
  filestore:
  db:
