#!/usr/bin/env bash

ADDONS=$(manifestoo --select-addons-dir src/private list --separator=, --sort=topological)
unbuffer odoo \
    -d ${PGDATABASE} \
    --reinit ${ADDONS} \
    --test-enable \
    --http-interface=0.0.0.0 \
    --stop-after-init | checklog-odoo -c src/private/.checklog-odoo
