#!/usr/bin/env bash

ADDONS=$(manifestoo --select-addons-dir src/private list --separator=, --sort=topological)
unbuffer odoo \
    -d ${PGDATABASE} \
    -i ${ADDONS} \
    --test-enable \
    --stop-after-init
