{
    "version": "15.0.0.1.0",
    "name": "brands_sale_stock",
    "summary": "Integrates sale_stock with brands",
    "category": "Sales",
    # 'live_test_url': "",
    "images": [],
    "application": True,
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "license": "Other proprietary",
    "depends": ["sale_stock", "brands"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/views.xml"],
    "qweb": [],
    "demo": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
