from . import account_analytic_line
from . import account_move
from . import glo_partner_time_balance
from . import glo_partner_time_balance_history
from . import helpdesk_team
from . import helpdesk_ticket
from . import hr_employee
from . import mail_message
from . import product_template
from . import res_partner
