{
    "version": "17.0.1.0.0",
    "name": "brands",
    "summary": "Allows a sale order and product to be associated with a brand",
    "category": "Sales",
    "application": True,
    "author": "Glo Networks",
    "website": "https://github.com/GlodoUK/odoo-addons",
    "license": "LGPL-3",
    "depends": ["sale", "product"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "security/ir.model.access.csv",
        "report/sale_report.xml",
        "report/account_invoice_report_view.xml",
        "data/data.xml",
        "views/account_move.xml",
        "views/brand.xml",
        "views/product_template.xml",
        "views/sale_order.xml",
        "views/document_layout_bold.xml",
        "views/document_layout_boxed.xml",
        "views/document_layout_standard.xml",
        "views/document_layout_stripped.xml",
    ],
}
