#!/usr/bin/env bash

mkdir -p src/odoo
mkdir -p src/enterprise
git clone --depth 1 --branch ${ODOO_VERSION} https://${GITHUB_TOKEN}@github.com/odoo/odoo.git src/odoo
git clone --depth 1 --branch ${ODOO_VERSION} https://${GITHUB_TOKEN}@github.com/GlodoUK/enterprise.git src/enterprise
