name: generate README

permissions:
  contents: write

on:
  push:
    branches:
      - "17.0"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: pre-commit/action@v3.0.1
        continue-on-error: true
        with:
          extra_args: --hook-stage=manual oca-gen-addons-table

      - name: commit changes
        run: |
          git config --global user.name "GlodoUK[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "ci: README generation from GitHub actions"
            git push
          fi
