name: tests

on:
  pull_request:
    branches:
      - "17.0*"
  push:
    branches:
      - "17.0"

env:
  UV_NO_CACHE: true
  UV_PYTHON_DOWNLOADS: never
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  DEBIAN_FRONTEND: noninteractive

jobs:
  unreleased-deps:
    runs-on: ubuntu-latest
    name: Detect unreleased dependencies
    steps:
      - uses: actions/checkout@v3
      - run: |
          for reqfile in requirements.txt test-requirements.txt ; do
              if [ -f ${reqfile} ] ; then
                  result=0
                  # reject non-comment lines that contain a / (i.e. URLs, relative paths)
                  grep "^[^#].*/" ${reqfile} || result=$?
                  if [ $result -eq 0 ] ; then
                      echo "Unreleased dependencies found in ${reqfile}."
                      exit 1
                  fi
              fi
          done
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
    name: Test
    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      PGHOST: odoo
      PGPASSWORD: odoo
      PGDATABASE: odoo
    steps:
      - name: Apt update and dependencies
        run: |
          apt-get -yqq update
          apt-get install -yqq --no-install-recommends \
            build-essential \
            libpq-dev \
            libldap2-dev \
            libsasl2-dev \
            libxml2-dev \
            libxslt-dev \
            libcurl4-openssl-dev \
            libssl-dev

      - uses: actions/checkout@v4
        with:
          repository: "odoo/odoo"
          ref: "17.0"
          persist-credentials: false
          path: odoo

      - uses: actions/checkout@v4
        with:
          repository: "GlodoUK/enterprise"
          ref: "17.0"
          persist-credentials: false
          path: enterprise
          token: ${{ secrets.GLODOUK_ENTERPRISE_GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: odoo-addons

      - run: |
          uv venv && \
            uv pip install -r odoo/requirements.txt && \
            uv pip install -e odoo && \
            uv pip install -r odoo-addons/requirements.txt && \
            uv pip install \
              click-odoo-contrib \
              manifestoo \
              checklog-odoo \
              coverage

      # Symlink workaround for https://github.com/astral-sh/uv/issues/2744
      - run: |
          ln -sf ${GITHUB_WORKSPACE}/odoo/odoo-bin ${GITHUB_WORKSPACE}/.venv/bin/odoo
          ls -la ${GITHUB_WORKSPACE}/.venv/bin/odoo

      - name: Init DB
        run: |
          uv run odoo -i base --addons-path=src/enterprise,src/odoo-addons --stop-after-init

      - run: |
          unbuffer uv run coverage run --include "src/odoo-addons/*" --branch \
              odoo \
              -i $(manifestoo --select-addons-dir src/odoo-addons list --separator=, --sort topological) \
              --test-enable \
              --stop-after-init | checklog-odoo
